### Creates a New Prompt
POST http://localhost:3000/prompts.json
Authorization: bearer  eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo1LCJleHAiOjE2Mzc4NzEzNjN9.LpRSgrEJiIwes4KDDaL4rLUfLUuBuSNbhrcJN3P_GiE
Content-Type: application/json

{
  "title": "Phantom",
  "content": "After moving into a house you discover that it is haunted."
}

### Updates a prompt
PATCH http://localhost:3000/prompts/7.json
Authorization: bearer  eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo1LCJleHAiOjE2Mzc4NzEzNjN9.LpRSgrEJiIwes4KDDaL4rLUfLUuBuSNbhrcJN3P_GiE
Content-Type: application/json

{
  "title": "This is a Test",
  "content": "While creating the backend for a website you are forced to run dozens of tests to make sure everything works."
}

### Deletes a prompt
DELETE http://localhost:3000/prompts/7.json
Authorization: bearer  eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo1LCJleHAiOjE2Mzc4NzEzNjN9.LpRSgrEJiIwes4KDDaL4rLUfLUuBuSNbhrcJN3P_GiE

### Creates a New User
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "first_name": "Amanda",
  "last_name": "Hale",
  "username": "amahal",
  "password": "password",
  "password_confirmation": "password"
}

### Creates a New Session
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "username": "devort",
  "password": "password"
}

### Shows List of Favorites
GET http://localhost:3000/favorites.json
Authorization: bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2Mzk2ODQ3MTB9.Lj8Hf0pij2mQTH13zaRdcMHpdYuucZMZrHGFh2rb7w4
Content-Type: application/json

### Creates a New Favorite
POST http://localhost:3000/favorites.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo3LCJleHAiOjE2Mzk2ODA0MDB9.hVyj667K76UN9R8iyNoDisyhX6mKXYkJxDmdg6NJQPo
Content-Type: application/json

{
  "prompt_id": 2
}

### Delete a Favorite
DELETE http://localhost:3000/favorites/5.json 
Authorization: bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2Mzc4NzIwMDl9.qxSdmDyqgx5M7goZGMifRF-HdTEirqNX8ei2Qj4_4y4